# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Vectorized version of `is.null`
#' @param x list
#' @rdname rcpp
#' @export
apply_is_null <- function(x) {
    .Call(`_cellpoptime_apply_is_null`, x)
}

